<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MovieSeeder extends Seeder
{
    // TMDB image base URLs — images are publicly accessible, no API key needed
    private string $poster = 'https://image.tmdb.org/t/p/w500';
    private string $backdrop = 'https://image.tmdb.org/t/p/w1280';

    public function run()
    {
        $now = date('Y-m-d H:i:s');

        $movies = [
            [
                'title' => 'The Shawshank Redemption',
                'slug' => 'the-shawshank-redemption',
                'description' => 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. A timeless story of hope and friendship inside the walls of Shawshank State Penitentiary.',
                'genre' => 'Drama',
                'year' => 1994,
                'duration' => 142,
                'rating' => 9.3,
                'poster_url' => $this->poster . '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
                'backdrop_url' => $this->backdrop . '/kXfqcdQKsToO0OUXHcrrNNriEc6.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=6hB3S9bIaco',
                'video_url' => '',
                'director' => 'Frank Darabont',
                'cast' => 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'The Godfather',
                'slug' => 'the-godfather',
                'description' => 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son. A sweeping saga of power, family loyalty, and the American dream turned dark.',
                'genre' => 'Crime',
                'year' => 1972,
                'duration' => 175,
                'rating' => 9.2,
                'poster_url' => $this->poster . '/3bhkrj58Vtu7enYsLLeNmzdaY81.jpg',
                'backdrop_url' => $this->backdrop . '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=sY1S34973zA',
                'video_url' => '',
                'director' => 'Francis Ford Coppola',
                'cast' => 'Marlon Brando, Al Pacino, James Caan, Diane Keaton',
                'is_featured' => 1,
                'is_trending' => 0,
            ],
            [
                'title' => 'The Dark Knight',
                'slug' => 'the-dark-knight',
                'description' => 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
                'genre' => 'Action',
                'year' => 2008,
                'duration' => 152,
                'rating' => 9.0,
                'poster_url' => $this->poster . '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'backdrop_url' => $this->backdrop . '/nMKdUFyrkzxzM8fmDWFaFVIWF5P.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
                'video_url' => '',
                'director' => 'Christopher Nolan',
                'cast' => 'Christian Bale, Heath Ledger, Aaron Eckhart, Maggie Gyllenhaal',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'Schindler\'s List',
                'slug' => 'schindlers-list',
                'description' => 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing the persecution of Jews in the streets.',
                'genre' => 'Drama',
                'year' => 1993,
                'duration' => 195,
                'rating' => 9.0,
                'poster_url' => $this->poster . '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
                'backdrop_url' => $this->backdrop . '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=mxphAlJID9U',
                'video_url' => '',
                'director' => 'Steven Spielberg',
                'cast' => 'Liam Neeson, Ralph Fiennes, Ben Kingsley, Embeth Davidtz',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Pulp Fiction',
                'slug' => 'pulp-fiction',
                'description' => 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption in 1990s Los Angeles.',
                'genre' => 'Crime',
                'year' => 1994,
                'duration' => 154,
                'rating' => 8.9,
                'poster_url' => $this->poster . '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
                'backdrop_url' => $this->backdrop . '/4cDFJr4HnXN5AdPw4AKrmLlMWdO.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
                'video_url' => '',
                'director' => 'Quentin Tarantino',
                'cast' => 'John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis',
                'is_featured' => 1,
                'is_trending' => 0,
            ],
            [
                'title' => 'Inception',
                'slug' => 'inception',
                'description' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team.',
                'genre' => 'Sci-Fi',
                'year' => 2010,
                'duration' => 148,
                'rating' => 8.8,
                'poster_url' => $this->poster . '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
                'backdrop_url' => $this->backdrop . '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
                'video_url' => '',
                'director' => 'Christopher Nolan',
                'cast' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'The Lord of the Rings: The Return of the King',
                'slug' => 'lotr-return-of-the-king',
                'description' => 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.',
                'genre' => 'Fantasy',
                'year' => 2003,
                'duration' => 201,
                'rating' => 9.0,
                'poster_url' => $this->poster . '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
                'backdrop_url' => $this->backdrop . '/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=r5X-hFf6Bwo',
                'video_url' => '',
                'director' => 'Peter Jackson',
                'cast' => 'Elijah Wood, Ian McKellen, Viggo Mortensen, Liv Tyler',
                'is_featured' => 0,
                'is_trending' => 1,
            ],
            [
                'title' => 'Forrest Gump',
                'slug' => 'forrest-gump',
                'description' => 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an extraordinary story.',
                'genre' => 'Drama',
                'year' => 1994,
                'duration' => 142,
                'rating' => 8.8,
                'poster_url' => $this->poster . '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
                'backdrop_url' => $this->backdrop . '/qdIMHd4sEoJBSZQIJ7fL8yFnV1H.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=bLvqoHBptjg',
                'video_url' => '',
                'director' => 'Robert Zemeckis',
                'cast' => 'Tom Hanks, Robin Wright, Gary Sinise, Sally Field',
                'is_featured' => 1,
                'is_trending' => 0,
            ],
            [
                'title' => 'Fight Club',
                'slug' => 'fight-club',
                'description' => 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much more sinister. A raw, anarchic exploration of masculinity and identity.',
                'genre' => 'Drama',
                'year' => 1999,
                'duration' => 139,
                'rating' => 8.8,
                'poster_url' => $this->poster . '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
                'backdrop_url' => $this->backdrop . '/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=qtRKdVHc-cE',
                'video_url' => '',
                'director' => 'David Fincher',
                'cast' => 'Brad Pitt, Edward Norton, Helena Bonham Carter, Meat Loaf',
                'is_featured' => 0,
                'is_trending' => 1,
            ],
            [
                'title' => 'Goodfellas',
                'slug' => 'goodfellas',
                'description' => 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.',
                'genre' => 'Crime',
                'year' => 1990,
                'duration' => 146,
                'rating' => 8.7,
                'poster_url' => $this->poster . '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
                'backdrop_url' => $this->backdrop . '/sw7mordbZxgITU877yTpZCud90M.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=2eyDlWKTRKY',
                'video_url' => '',
                'director' => 'Martin Scorsese',
                'cast' => 'Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'The Matrix',
                'slug' => 'the-matrix',
                'description' => 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers. Reality is not what it seems.',
                'genre' => 'Sci-Fi',
                'year' => 1999,
                'duration' => 136,
                'rating' => 8.7,
                'poster_url' => $this->poster . '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
                'backdrop_url' => $this->backdrop . '/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
                'video_url' => '',
                'director' => 'Lana Wachowski, Lilly Wachowski',
                'cast' => 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'Interstellar',
                'slug' => 'interstellar',
                'description' => 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival as Earth faces environmental collapse. Love transcends dimensions of time and space.',
                'genre' => 'Sci-Fi',
                'year' => 2014,
                'duration' => 169,
                'rating' => 8.7,
                'poster_url' => $this->poster . '/gEU2QniE6E77NI6lCU6MxlNBvIe.jpg',
                'backdrop_url' => $this->backdrop . '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
                'video_url' => '',
                'director' => 'Christopher Nolan',
                'cast' => 'Matthew McConaughey, Anne Hathaway, Jessica Chastain, Matt Damon',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'Parasite',
                'slug' => 'parasite',
                'description' => 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan. A biting social satire from Bong Joon-ho.',
                'genre' => 'Thriller',
                'year' => 2019,
                'duration' => 132,
                'rating' => 8.5,
                'poster_url' => $this->poster . '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
                'backdrop_url' => $this->backdrop . '/ApiBzeaa95TNYLSKkEWbW8Co7bQ.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=5xH0HfJHsaY',
                'video_url' => '',
                'director' => 'Bong Joon-ho',
                'cast' => 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'Joker',
                'slug' => 'joker',
                'description' => 'A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain. Arthur Fleck\'s transformation into chaos incarnate.',
                'genre' => 'Drama',
                'year' => 2019,
                'duration' => 122,
                'rating' => 8.4,
                'poster_url' => $this->poster . '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
                'backdrop_url' => $this->backdrop . '/f5F4cRhQdUbyVbB5lTNCwUzD6BP.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
                'video_url' => '',
                'director' => 'Todd Phillips',
                'cast' => 'Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'Avengers: Endgame',
                'slug' => 'avengers-endgame',
                'description' => 'After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos\'s actions and restore balance to the universe. The ultimate Marvel showdown.',
                'genre' => 'Action',
                'year' => 2019,
                'duration' => 181,
                'rating' => 8.4,
                'poster_url' => $this->poster . '/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
                'backdrop_url' => $this->backdrop . '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
                'video_url' => '',
                'director' => 'Anthony Russo, Joe Russo',
                'cast' => 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'Dune',
                'slug' => 'dune-2021',
                'description' => 'Feature adaptation of Frank Herbert\'s science fiction novel about the son of a noble family tasked with protecting the most valuable asset in the galaxy on the desert planet Arrakis.',
                'genre' => 'Sci-Fi',
                'year' => 2021,
                'duration' => 155,
                'rating' => 8.0,
                'poster_url' => $this->poster . '/d5NXSklXo0qyIYkgV48Ze6Ai4LW.jpg',
                'backdrop_url' => $this->backdrop . '/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=8g18jFHCLXk',
                'video_url' => '',
                'director' => 'Denis Villeneuve',
                'cast' => 'Timothée Chalamet, Rebecca Ferguson, Oscar Isaac, Zendaya',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'Top Gun: Maverick',
                'slug' => 'top-gun-maverick',
                'description' => 'After more than thirty years of service as a top naval aviator, Pete Mitchell is pushing the envelope as a courageous test pilot while dodging the advancement in rank that would ground him.',
                'genre' => 'Action',
                'year' => 2022,
                'duration' => 130,
                'rating' => 8.3,
                'poster_url' => $this->poster . '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
                'backdrop_url' => $this->backdrop . '/AbRYgCbl0MH0STfASzFbJDdDyAh.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=giXco2jaZ_4',
                'video_url' => '',
                'director' => 'Joseph Kosinski',
                'cast' => 'Tom Cruise, Jennifer Connelly, Miles Teller, Val Kilmer',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'Oppenheimer',
                'slug' => 'oppenheimer',
                'description' => 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II. A masterwork from Christopher Nolan.',
                'genre' => 'Drama',
                'year' => 2023,
                'duration' => 180,
                'rating' => 8.4,
                'poster_url' => $this->poster . '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
                'backdrop_url' => $this->backdrop . '/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=uYPbbksJxIg',
                'video_url' => '',
                'director' => 'Christopher Nolan',
                'cast' => 'Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr.',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'The Batman',
                'slug' => 'the-batman-2022',
                'description' => 'When the Riddler, a sadistic serial killer, begins murdering key political figures in Gotham, Batman is forced to investigate the city\'s hidden corruption.',
                'genre' => 'Action',
                'year' => 2022,
                'duration' => 176,
                'rating' => 7.8,
                'poster_url' => $this->poster . '/74xTEgt7R36Fpocon6bTFOfHqBO.jpg',
                'backdrop_url' => $this->backdrop . '/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
                'video_url' => '',
                'director' => 'Matt Reeves',
                'cast' => 'Robert Pattinson, Zoë Kravitz, Jeffrey Wright, Colin Farrell',
                'is_featured' => 0,
                'is_trending' => 1,
            ],
            [
                'title' => 'Spider-Man: No Way Home',
                'slug' => 'spider-man-no-way-home',
                'description' => 'With Spider-Man\'s identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.',
                'genre' => 'Action',
                'year' => 2021,
                'duration' => 148,
                'rating' => 8.2,
                'poster_url' => $this->poster . '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
                'backdrop_url' => $this->backdrop . '/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
                'video_url' => '',
                'director' => 'Jon Watts',
                'cast' => 'Tom Holland, Zendaya, Benedict Cumberbatch, Willem Dafoe',
                'is_featured' => 0,
                'is_trending' => 1,
            ],
            [
                'title' => 'Gladiator',
                'slug' => 'gladiator',
                'description' => 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery. What we do in life echoes in eternity.',
                'genre' => 'Action',
                'year' => 2000,
                'duration' => 155,
                'rating' => 8.5,
                'poster_url' => $this->poster . '/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
                'backdrop_url' => $this->backdrop . '/gF4gKFPrVehUCwyL4BqSqFDwMom.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=owK1qxDselE',
                'video_url' => '',
                'director' => 'Ridley Scott',
                'cast' => 'Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Titanic',
                'slug' => 'titanic',
                'description' => 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic. An epic romance against the backdrop of the greatest maritime disaster.',
                'genre' => 'Romance',
                'year' => 1997,
                'duration' => 194,
                'rating' => 7.9,
                'poster_url' => $this->poster . '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
                'backdrop_url' => $this->backdrop . '/kHXEpqv8qKUV0bGmAdMeUpgFvQ0.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=kVrqfYjkTdQ',
                'video_url' => '',
                'director' => 'James Cameron',
                'cast' => 'Leonardo DiCaprio, Kate Winslet, Billy Zane, Frances Fisher',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Whiplash',
                'slug' => 'whiplash',
                'description' => 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
                'genre' => 'Drama',
                'year' => 2014,
                'duration' => 106,
                'rating' => 8.5,
                'poster_url' => $this->poster . '/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
                'backdrop_url' => $this->backdrop . '/6bbZ6XyvgfjhQwbplnUh1LSj1uu.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=7d_jQycdQGo',
                'video_url' => '',
                'director' => 'Damien Chazelle',
                'cast' => 'Miles Teller, J.K. Simmons, Melissa Benoist, Paul Reiser',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'The Silence of the Lambs',
                'slug' => 'the-silence-of-the-lambs',
                'description' => 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
                'genre' => 'Thriller',
                'year' => 1991,
                'duration' => 118,
                'rating' => 8.6,
                'poster_url' => $this->poster . '/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
                'backdrop_url' => $this->backdrop . '/mfwq2nMBmAT7VCSLX7LQKJBZOEQ.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=W6Mm8Sbe__o',
                'video_url' => '',
                'director' => 'Jonathan Demme',
                'cast' => 'Jodie Foster, Anthony Hopkins, Lawrence A. Bonney, Kasi Lemmons',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Avatar',
                'slug' => 'avatar',
                'description' => 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
                'genre' => 'Sci-Fi',
                'year' => 2009,
                'duration' => 162,
                'rating' => 7.9,
                'poster_url' => $this->poster . '/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg',
                'backdrop_url' => $this->backdrop . '/o0s4XsEDfDlvit5pDRtjn9soJkc.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=5PSNL1qE6VY',
                'video_url' => '',
                'director' => 'James Cameron',
                'cast' => 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Michelle Rodriguez',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Everything Everywhere All at Once',
                'slug' => 'everything-everywhere-all-at-once',
                'description' => 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.',
                'genre' => 'Sci-Fi',
                'year' => 2022,
                'duration' => 139,
                'rating' => 8.1,
                'poster_url' => $this->poster . '/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
                'backdrop_url' => $this->backdrop . '/yHCfW4Tr34QqgEHJVBBBFxQSz6m.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=wxN1T1uxQ2g',
                'video_url' => '',
                'director' => 'Daniel Kwan, Daniel Scheinert',
                'cast' => 'Michelle Yeoh, Ke Huy Quan, Jamie Lee Curtis, Stephanie Hsu',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'Black Panther',
                'slug' => 'black-panther',
                'description' => 'T\'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and must confront a challenger from his country\'s past.',
                'genre' => 'Action',
                'year' => 2018,
                'duration' => 134,
                'rating' => 7.3,
                'poster_url' => $this->poster . '/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
                'backdrop_url' => $this->backdrop . '/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=xjDjIWPwcPU',
                'video_url' => '',
                'director' => 'Ryan Coogler',
                'cast' => 'Chadwick Boseman, Michael B. Jordan, Lupita Nyong\'o, Danai Gurira',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Get Out',
                'slug' => 'get-out',
                'description' => 'A young African-American visits his white girlfriend\'s parents for the weekend, where his stay reveals an unimaginable secret. Jordan Peele\'s brilliant social horror debut.',
                'genre' => 'Horror',
                'year' => 2017,
                'duration' => 104,
                'rating' => 7.7,
                'poster_url' => $this->poster . '/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg',
                'backdrop_url' => $this->backdrop . '/iEFuHjqrMQaHSCwIRBklqOrFXPk.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=DzfpyUB60YY',
                'video_url' => '',
                'director' => 'Jordan Peele',
                'cast' => 'Daniel Kaluuya, Allison Williams, Bradley Whitford, Catherine Keener',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Mad Max: Fury Road',
                'slug' => 'mad-max-fury-road',
                'description' => 'In a post-apocalyptic wasteland, Max teams up with a mysterious woman, Furiosa, to help a group of female prisoners escape a tyrannical warlord. A breathtaking action spectacle.',
                'genre' => 'Action',
                'year' => 2015,
                'duration' => 120,
                'rating' => 8.1,
                'poster_url' => $this->poster . '/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
                'backdrop_url' => $this->backdrop . '/phszHPFnhmSgRDbRBkhJSlFEKdB.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=hEJnMQG9ev8',
                'video_url' => '',
                'director' => 'George Miller',
                'cast' => 'Tom Hardy, Charlize Theron, Nicholas Hoult, Hugh Keays-Byrne',
                'is_featured' => 0,
                'is_trending' => 1,
            ],
            [
                'title' => 'La La Land',
                'slug' => 'la-la-land',
                'description' => 'While navigating their careers in Los Angeles, a pianist and an actress share an inspiring romance while attempting to reconcile their art and ambitions as success threatens their relationship.',
                'genre' => 'Romance',
                'year' => 2016,
                'duration' => 128,
                'rating' => 8.0,
                'poster_url' => $this->poster . '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
                'backdrop_url' => $this->backdrop . '/nadTlnTE6dDyMzHKSFPBDEdxjcI.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=0pdqf4P9MB8',
                'video_url' => '',
                'director' => 'Damien Chazelle',
                'cast' => 'Ryan Gosling, Emma Stone, John Legend, Rosemarie DeWitt',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Blade Runner 2049',
                'slug' => 'blade-runner-2049',
                'description' => 'A young blade runner\'s discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who\'s been missing for thirty years. A stunning sci-fi noir.',
                'genre' => 'Sci-Fi',
                'year' => 2017,
                'duration' => 164,
                'rating' => 8.0,
                'poster_url' => $this->poster . '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
                'backdrop_url' => $this->backdrop . '/ilRyazdMfOUdzuluz6i9rMA0yGQ.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=gCcx85zbxz4',
                'video_url' => '',
                'director' => 'Denis Villeneuve',
                'cast' => 'Ryan Gosling, Harrison Ford, Ana de Armas, Sylvia Hoeks',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Arrival',
                'slug' => 'arrival',
                'description' => 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world. A profound meditation on language and time.',
                'genre' => 'Sci-Fi',
                'year' => 2016,
                'duration' => 116,
                'rating' => 7.9,
                'poster_url' => $this->poster . '/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
                'backdrop_url' => $this->backdrop . '/imgqnhGCsFtPVuKABQxAiXAK9Rc.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=tFMo3UJ4B4g',
                'video_url' => '',
                'director' => 'Denis Villeneuve',
                'cast' => 'Amy Adams, Jeremy Renner, Forest Whitaker, Michael Stuhlbarg',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'The Avengers',
                'slug' => 'the-avengers',
                'description' => 'Earth\'s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.',
                'genre' => 'Action',
                'year' => 2012,
                'duration' => 143,
                'rating' => 8.0,
                'poster_url' => $this->poster . '/RYMX2wcKCBAr24UyPD7KE3Ouxml.jpg',
                'backdrop_url' => $this->backdrop . '/o7qi2v4uWaZA2hcnEHrLDF0HnYi.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=eOrNdBpGMv8',
                'video_url' => '',
                'director' => 'Joss Whedon',
                'cast' => 'Robert Downey Jr., Chris Evans, Scarlett Johansson, Mark Ruffalo',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'No Country for Old Men',
                'slug' => 'no-country-for-old-men',
                'description' => 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande. A chilling study in evil.',
                'genre' => 'Thriller',
                'year' => 2007,
                'duration' => 122,
                'rating' => 8.2,
                'poster_url' => $this->poster . '/6d5XOczc62gBpSGNqAFIeB8gKpb.jpg',
                'backdrop_url' => $this->backdrop . '/wa8ND7GhEKMSQx3oFECPbGI9MId.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=38A__WT3-o0',
                'video_url' => '',
                'director' => 'Joel Coen, Ethan Coen',
                'cast' => 'Tommy Lee Jones, Javier Bardem, Josh Brolin, Kelly Macdonald',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Django Unchained',
                'slug' => 'django-unchained',
                'description' => 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner. Tarantino\'s revisionist spaghetti western.',
                'genre' => 'Western',
                'year' => 2012,
                'duration' => 165,
                'rating' => 8.5,
                'poster_url' => $this->poster . '/7oWY8VDWW7thTzWh3OKYRkWgNqi.jpg',
                'backdrop_url' => $this->backdrop . '/2oZklIzUbvZXXzIFzv7Hi8bNhNj.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=eUdM9vrCbow',
                'video_url' => '',
                'director' => 'Quentin Tarantino',
                'cast' => 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'The Wolf of Wall Street',
                'slug' => 'the-wolf-of-wall-street',
                'description' => 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.',
                'genre' => 'Drama',
                'year' => 2013,
                'duration' => 180,
                'rating' => 8.2,
                'poster_url' => $this->poster . '/34m2tygAYBGqA9MXKhRDtzYd4Ja.jpg',
                'backdrop_url' => $this->backdrop . '/rT0nEHfbucJhSRnkIuqhZR6XFEI.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=iszwuX1AK6A',
                'video_url' => '',
                'director' => 'Martin Scorsese',
                'cast' => 'Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey',
                'is_featured' => 0,
                'is_trending' => 1,
            ],
            [
                'title' => 'Hereditary',
                'slug' => 'hereditary',
                'description' => 'A grieving family is haunted by tragic and disturbing occurrences after the death of their secretive grandmother. Ari Aster\'s terrifying portrait of familial grief and horror.',
                'genre' => 'Horror',
                'year' => 2018,
                'duration' => 127,
                'rating' => 7.3,
                'poster_url' => $this->poster . '/mXLOHHc1Zeuwsl4xYKjKh2280oL.jpg',
                'backdrop_url' => $this->backdrop . '/fPEkdpu37f0Q9ADYX7FJpOKhMNq.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=V6wWKNij_1M',
                'video_url' => '',
                'director' => 'Ari Aster',
                'cast' => 'Toni Collette, Alex Wolff, Milly Shapiro, Gabriel Byrne',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Knives Out',
                'slug' => 'knives-out',
                'description' => 'A detective investigates the death of a patriarch of an eccentric, combative family. Rian Johnson\'s clever, crowd-pleasing whodunit with a stellar ensemble cast.',
                'genre' => 'Thriller',
                'year' => 2019,
                'duration' => 130,
                'rating' => 7.9,
                'poster_url' => $this->poster . '/pThyQovXQrws2Y4vudOdR4UWKL7.jpg',
                'backdrop_url' => $this->backdrop . '/2X3BIhApVjMdCkumGRrOghIZBcp.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=qGqiHJTsRkQ',
                'video_url' => '',
                'director' => 'Rian Johnson',
                'cast' => 'Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'John Wick',
                'slug' => 'john-wick',
                'description' => 'An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him. A sleek, stylish action thriller that redefined the genre.',
                'genre' => 'Action',
                'year' => 2014,
                'duration' => 101,
                'rating' => 7.4,
                'poster_url' => $this->poster . '/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
                'backdrop_url' => $this->backdrop . '/umC04Cozevu8nn3ZTIU9rp7qIed.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=2AUmvWm5ZDQ',
                'video_url' => '',
                'director' => 'Chad Stahelski',
                'cast' => 'Keanu Reeves, Michael Nyqvist, Alfie Allen, Adrianne Palicki',
                'is_featured' => 0,
                'is_trending' => 1,
            ],
            [
                'title' => 'The Grand Budapest Hotel',
                'slug' => 'the-grand-budapest-hotel',
                'description' => 'A writer encounters the owner of an aging European hotel between the wars and learns of his friendship with a young employee who becomes involved in the theft of a priceless painting and a family battle over a great fortune.',
                'genre' => 'Comedy',
                'year' => 2014,
                'duration' => 100,
                'rating' => 8.1,
                'poster_url' => $this->poster . '/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
                'backdrop_url' => $this->backdrop . '/sDLZEHYr9Bww4AsESnTsZJ0mxJM.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=1Fg5iWmQjwk',
                'video_url' => '',
                'director' => 'Wes Anderson',
                'cast' => 'Ralph Fiennes, Tony Revolori, Saoirse Ronan, F. Murray Abraham',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Soul',
                'slug' => 'soul-pixar',
                'description' => 'After landing the gig of his life, a New York jazz pianist suddenly finds himself trapped in a strange land between Earth and the afterlife. A Pixar masterpiece about finding your spark.',
                'genre' => 'Animation',
                'year' => 2020,
                'duration' => 100,
                'rating' => 8.1,
                'poster_url' => $this->poster . '/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
                'backdrop_url' => $this->backdrop . '/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=xOsLIiBStEs',
                'video_url' => '',
                'director' => 'Pete Docter',
                'cast' => 'Jamie Foxx, Tina Fey, Graham Norton, Rachel House',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Coco',
                'slug' => 'coco-pixar',
                'description' => 'Aspiring musician Miguel, confronted with his family\'s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.',
                'genre' => 'Animation',
                'year' => 2017,
                'duration' => 105,
                'rating' => 8.4,
                'poster_url' => $this->poster . '/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
                'backdrop_url' => $this->backdrop . '/askg3SMvhqEl4OL52YuvdtY40Yb.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=Ga6RYejo6Hk',
                'video_url' => '',
                'director' => 'Lee Unkrich',
                'cast' => 'Anthony Gonzalez, Gael García Bernal, Benjamin Bratt, Alanna Ubach',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'A Quiet Place',
                'slug' => 'a-quiet-place',
                'description' => 'In a post-apocalyptic world, a family is forced to live in near silence while hiding from creatures that hunt by sound. John Krasinski\'s masterfully tense horror film.',
                'genre' => 'Horror',
                'year' => 2018,
                'duration' => 90,
                'rating' => 7.5,
                'poster_url' => $this->poster . '/nAU74GmpUk7t5iklEp3bufwDq4n.jpg',
                'backdrop_url' => $this->backdrop . '/roYyPiQKEzLxY5UKvbfIuvhGpeO.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=WR7cc5t7tv8',
                'video_url' => '',
                'director' => 'John Krasinski',
                'cast' => 'Emily Blunt, John Krasinski, Millicent Simmonds, Noah Jupe',
                'is_featured' => 0,
                'is_trending' => 0,
            ],
            [
                'title' => 'Dune: Part Two',
                'slug' => 'dune-part-two',
                'description' => 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. An epic continuation of the Dune saga.',
                'genre' => 'Sci-Fi',
                'year' => 2024,
                'duration' => 166,
                'rating' => 8.5,
                'poster_url' => $this->poster . '/8b8R8l88Qje9dn9OE8PY05Nxl1Z.jpg',
                'backdrop_url' => $this->backdrop . '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=Way9Dexny3w',
                'video_url' => '',
                'director' => 'Denis Villeneuve',
                'cast' => 'Timothée Chalamet, Zendaya, Rebecca Ferguson, Austin Butler',
                'is_featured' => 1,
                'is_trending' => 1,
            ],
            [
                'title' => 'Poor Things',
                'slug' => 'poor-things',
                'description' => 'The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.',
                'genre' => 'Drama',
                'year' => 2023,
                'duration' => 141,
                'rating' => 8.0,
                'poster_url' => $this->poster . '/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg',
                'backdrop_url' => $this->backdrop . '/bQmEmkky41m2bDQbD5fHLDCBBqy.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=RlbR5N6veqw',
                'video_url' => '',
                'director' => 'Yorgos Lanthimos',
                'cast' => 'Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Youssef',
                'is_featured' => 0,
                'is_trending' => 1,
            ],
            [
                'title' => 'Killers of the Flower Moon',
                'slug' => 'killers-of-the-flower-moon',
                'description' => 'Members of the Osage Nation are murdered under mysterious circumstances in 1920s Oklahoma, sparking a major FBI investigation involving a web of corruption and deceit.',
                'genre' => 'Crime',
                'year' => 2023,
                'duration' => 206,
                'rating' => 7.6,
                'poster_url' => $this->poster . '/dB6Krk806zeqd1psiCaFXLoLxj2.jpg',
                'backdrop_url' => $this->backdrop . '/1X7vow16X7CnCoK9Drmqy1GUn74.jpg',
                'trailer_url' => 'https://www.youtube.com/watch?v=EP34Yoxs3FQ',
                'video_url' => '',
                'director' => 'Martin Scorsese',
                'cast' => 'Leonardo DiCaprio, Robert De Niro, Lily Gladstone, Jesse Plemons',
                'is_featured' => 0,
                'is_trending' => 1,
            ],
        ];

        // Add timestamps
        foreach ($movies as &$m) {
            $m['created_at'] = $now;
            $m['updated_at'] = $now;
        }

        $this->db->table('movies')->insertBatch($movies);
        echo "Seeded " . count($movies) . " real movies with TMDB image URLs.\n";
    }
}
