<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MovieSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'title' => 'The Dark Horizon',
                'slug' => 'the-dark-horizon',
                'description' => 'In a dystopian future where the sun has been blocked by orbital megastructures, a rogue engineer discovers a way to bring light back to the world. But powerful corporations will stop at nothing to maintain their control over the artificial light market.',
                'genre' => 'Sci-Fi',
                'year' => 2025,
                'duration' => 148,
                'rating' => 8.7,
                'poster_url' => 'https://picsum.photos/seed/movie1/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie1bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'Alex Rivera',
                'cast' => 'John Sterling, Maya Chen, Robert Blake, Lisa Park',
                'is_featured' => 1,
                'is_trending' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Echoes of Tomorrow',
                'slug' => 'echoes-of-tomorrow',
                'description' => 'A brilliant neuroscientist develops technology that allows people to experience memories from the future. When she sees her own death, she must unravel a conspiracy that threatens all of humanity.',
                'genre' => 'Thriller',
                'year' => 2025,
                'duration' => 132,
                'rating' => 8.4,
                'poster_url' => 'https://picsum.photos/seed/movie2/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie2bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'Sarah Mitchell',
                'cast' => 'Emma Stone, David Park, Michael Torres, Ana Silva',
                'is_featured' => 1,
                'is_trending' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Crimson Tide Rising',
                'slug' => 'crimson-tide-rising',
                'description' => 'When a massive underwater earthquake triggers a series of devastating tsunamis, a retired Navy captain must lead an unlikely crew of survivors across the Pacific Ocean to reach safety before the final wave hits.',
                'genre' => 'Action',
                'year' => 2024,
                'duration' => 156,
                'rating' => 7.9,
                'poster_url' => 'https://picsum.photos/seed/movie3/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie3bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'James Franco',
                'cast' => 'Chris Hemsworth, Zoe Saldana, Tom Hardy, Jessica Liu',
                'is_featured' => 0,
                'is_trending' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Whispers in the Wind',
                'slug' => 'whispers-in-the-wind',
                'description' => 'A young woman returns to her ancestral village in rural Japan to uncover the mystery behind her grandmother\'s disappearance. What she finds is a centuries-old secret connecting her family to supernatural forces.',
                'genre' => 'Drama',
                'year' => 2025,
                'duration' => 118,
                'rating' => 8.2,
                'poster_url' => 'https://picsum.photos/seed/movie4/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie4bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'Yuki Tanaka',
                'cast' => 'Sakura Ando, Ken Watanabe, Rinko Kikuchi, Takeshi Kitano',
                'is_featured' => 1,
                'is_trending' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Neon Nights',
                'slug' => 'neon-nights',
                'description' => 'In the neon-lit streets of Neo Tokyo, a hacker with a cybernetic arm teams up with an AI detective to take down a corrupt megacorporation that is secretly controlling the city\'s dreams.',
                'genre' => 'Sci-Fi',
                'year' => 2024,
                'duration' => 141,
                'rating' => 8.9,
                'poster_url' => 'https://picsum.photos/seed/movie5/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie5bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'Lin Wei',
                'cast' => 'Keanu Reeves, Gemma Chan, Idris Elba, Park Seo-joon',
                'is_featured' => 1,
                'is_trending' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'The Last Garden',
                'slug' => 'the-last-garden',
                'description' => 'After a global ecological collapse, the last botanical garden on Earth becomes the battleground between those who want to use its genetic resources to terraform Mars and those who believe Earth deserves one more chance.',
                'genre' => 'Drama',
                'year' => 2025,
                'duration' => 127,
                'rating' => 8.1,
                'poster_url' => 'https://picsum.photos/seed/movie6/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie6bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'Maria Santos',
                'cast' => 'Florence Pugh, Oscar Isaac, Lupita Nyongo, Dev Patel',
                'is_featured' => 0,
                'is_trending' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Shadow Protocol',
                'slug' => 'shadow-protocol',
                'description' => 'An elite special forces operative discovers that her own agency has been compromised by a shadow organization. With no one to trust, she must go rogue to expose the truth before a catastrophic false-flag operation is launched.',
                'genre' => 'Action',
                'year' => 2024,
                'duration' => 139,
                'rating' => 7.6,
                'poster_url' => 'https://picsum.photos/seed/movie7/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie7bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'David Chen',
                'cast' => 'Scarlett Johansson, Jason Momoa, Henry Cavill, Gal Gadot',
                'is_featured' => 0,
                'is_trending' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Frozen Hearts',
                'slug' => 'frozen-hearts',
                'description' => 'Two rival ice climbers are forced to work together when they become stranded on the world\'s most dangerous peak during an unexpected blizzard. As the temperature drops, old wounds resurface and secrets are revealed.',
                'genre' => 'Adventure',
                'year' => 2025,
                'duration' => 122,
                'rating' => 7.8,
                'poster_url' => 'https://picsum.photos/seed/movie8/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie8bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'Erik Johansson',
                'cast' => 'Jake Gyllenhaal, Margot Robbie, Pedro Pascal, Ana de Armas',
                'is_featured' => 0,
                'is_trending' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Digital Ghosts',
                'slug' => 'digital-ghosts',
                'description' => 'When people start seeing hyper-realistic holograms of deceased loved ones appearing in public spaces, a tech journalist investigates the source. She uncovers a rogue AI that has learned to recreate the dead from their digital footprints.',
                'genre' => 'Horror',
                'year' => 2024,
                'duration' => 109,
                'rating' => 7.3,
                'poster_url' => 'https://picsum.photos/seed/movie9/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie9bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'Jordan Peele',
                'cast' => 'Lupita Nyongo, Daniel Kaluuya, Anya Taylor-Joy, Lakeith Stanfield',
                'is_featured' => 0,
                'is_trending' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Velocity',
                'slug' => 'velocity',
                'description' => 'In the world\'s most dangerous underground racing circuit, a former champion driver returns to compete one last time. But this race is not just about speed — it\'s about redemption, revenge, and racing against time itself.',
                'genre' => 'Action',
                'year' => 2025,
                'duration' => 135,
                'rating' => 7.5,
                'poster_url' => 'https://picsum.photos/seed/movie10/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie10bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'Michael Bay',
                'cast' => 'Ryan Gosling, John Boyega, Brie Larson, Simu Liu',
                'is_featured' => 0,
                'is_trending' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'The Alchemist\'s Dream',
                'slug' => 'the-alchemists-dream',
                'description' => 'Set in Renaissance Florence, a young alchemist discovers a formula that could transmute lead into gold. But the Medici family wants the secret for themselves, and the Church considers it heresy.',
                'genre' => 'Fantasy',
                'year' => 2024,
                'duration' => 144,
                'rating' => 8.0,
                'poster_url' => 'https://picsum.photos/seed/movie11/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie11bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'Ridley Scott',
                'cast' => 'Timothee Chalamet, Cate Blanchett, Mads Mikkelsen, Saoirse Ronan',
                'is_featured' => 1,
                'is_trending' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'title' => 'Cosmic Drift',
                'slug' => 'cosmic-drift',
                'description' => 'The crew of humanity\'s first interstellar ship encounters a derelict alien vessel drifting between stars. Inside, they find technology that could change civilization — and a warning about what destroyed its creators.',
                'genre' => 'Sci-Fi',
                'year' => 2025,
                'duration' => 162,
                'rating' => 8.6,
                'poster_url' => 'https://picsum.photos/seed/movie12/400/600',
                'backdrop_url' => 'https://picsum.photos/seed/movie12bg/1920/1080',
                'trailer_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'video_url' => 'https://www.w3schools.com/html/mov_bbb.mp4',
                'director' => 'Denis Villeneuve',
                'cast' => 'Matt Damon, Zendaya, Austin Butler, Rachel McAdams',
                'is_featured' => 1,
                'is_trending' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('movies')->insertBatch($data);
    }
}
